### ISSUE TITLE
[dev] Make sure that we retrieve an IP from glocaltokens

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/ha-glocaltokens#36]
Make sure that we get an IP from glocaltokens or else throw an error or something.

**Comment by leikoilja** [comment]
Should we implement it on `glocaltokens` package level? I think the check has to be inside `ha-google-home`. We could probs log a warning/error and ignore the entities without IP address when starting up? 

Sorry it it's non-intuitive or confusing, I was thinking of using `glocaltokens` github label for tasks relying to be fixed on the python package.

**Comment by DurgNomis-drol** [comment]
No you are right, i just misunderstood the use of glocaltokens.

I will submit a fix making it a warning after I have confirmed that we get the IP. As of now we don't, and i don't know why. See issue over at `glocaltokens` 🤔

**Comment by ArnyminerZ** [comment]
@leikoilja I think it should be implemented here. As you have said, showing a warning, and not showing the device. Because, it might happen (I'm not sure), that the device is added in your Google Account (Homegraph), but disconnected from the network. So `glocaltokens` would still show you the device, but `ha-google-home` would not show it to the user.

**Comment by leikoilja** [comment]
Guys, i have been thinking about it... as @ArnyminerZ have mentioned it might happen that the device is existing but we fail to retrieve IP address. Like what if the google home was disconnected from power or something.. So i propose we do a `status` attribute on the Google device in this integration and set it to `offline` if we fail to fetch IP address? That way we can check IP addresses quite often and if some are not found we won't remove or hide existing devices, but rather just make them "offline"?

**Comment by ArnyminerZ** [comment]
That would be really convenient, and an awesome way to tell the user there was a kind of error.

**Comment by DurgNomis-drol** [comment]
See [here](https://github.com/leikoilja/glocaltokens/issues/28#issuecomment-781466485)

**Comment by DurgNomis-drol** [comment]
It still returns ip `None`, same for port

`{'device_name': 'Simons TV', 'local_auth_token': 'mytoken', 'google_device': {'ip': None, 'port': None}}`

**Comment by leikoilja** [comment]
Yes, that's the expected behavior. `glocaltokens` is not supposed to fetch IP/port, we will utilize HA `zeroconf` instance for that. And the warning is gone because we disabled the `zeroconf` in `glocaltokens`. 
We should create a separate issue for device autodiscovery within HA utilizing their `zeroconf`

**Comment by DurgNomis-drol** [comment]
Okay, i just missundeostrod it then.

**Comment by leikoilja** [comment]
No worries 😄  Here we go - https://github.com/leikoilja/ha-glocaltokens/issues/40
